/**
 * DailySelfieContract.java
 * Created on: Nov 25, 2014
 * For the sole purpose of the Just DO! ussage.
 * All rights reserved.
 */
package org.tjdo.dailyselfie.provider;

import android.net.Uri;

/**
 * Defines all contract parameters to be used on providers 
 * and the main application.
 * @author efmcuiti
 *
 */
public final class DailySelfieContract {

	/** Used to locate the content provider. */
	public static final String AUTHORITY = "org.tjdo.dailyselfie.provider";
	
	/** Constructed based on the authority location. */
	public static final Uri BASE_URI = Uri.parse("content://" + AUTHORITY + "/");
	
	/** Where to look for the pictures. */
	public static final String SELFIES_TABLE_NAME = "selfies";
	
	/** All of the above are considered just for this last constant. */
	public static final Uri CONTENT_URI = Uri.withAppendedPath(BASE_URI, SELFIES_TABLE_NAME);
	
	/** Column for the auto-generated identifier. */
	public static final String _ID = "_id";
	/** Path where to find in the device a picture. */
	public static final String SELFIE_BITMAP_PATH = "selfie_bitmap_path";
	/** Autogenerated name of the selfie. */
	public static final String SELFIE_NAME = "selfie_name";
}
